### ISSUE TITLE
Microsoft Fluent Design

### ISSUE THREAD

**Issue by vanillajonathan** [penpot/penpot-files#13]
I request a Penpot file for Microsoft Fluent Design.

https://www.microsoft.com/design/fluent/

**Comment by EvaMarco** [comment]
Hello @vanillajonathan 
Just kindly remind you that we are open to contributions :), you have a guide [here](https://penpot.app/how-to-contribute.html).
Also if you can not contribute with this you can ask for help in the [community]( https://community.penpot.app/). 
Thanks¡¡
