### ISSUE TITLE
Update Material UI

### ISSUE THREAD

**Issue by ggtylerr** [penpot/penpot-files#14]
The Material Design Kit is heavily outdated. Most notable thing is Material 3, but even Material 2 is missing a lot of elements (backdrops, dropdown menus, image lists, data tables, tabs, etc.)

**Comment by jonathan-chin** [comment]
I'm considering adopting PenPot into my workflow. I use Material UI on a number of projects and would like to draft them with PenPot; however, if the library is outdated, then that would be a huge roadblock.

**Comment by myfunnyandy** [comment]
We are willing to create the M3 library but thruth is that we are currently focused on the Penpot product development and it might be a while until we can make it into our priorities. You might want to ask for help at the community ast most of the templates are made by community members outside the Penpot team. There is an specific tag for libraries and templates that you could use: https://community.penpot.app/c/contributions/libraries-templates
