### ISSUE TITLE
Arcticons icons as a library

### ISSUE THREAD

**Issue by Donnnno** [penpot/penpot-files#15]
Hi, I'm the creator of the [Arcticons icon pack](https://github.com/Donnnno/Arcticons), and I recently found out it can be easily compatible as a library, like here:

https://icon-sets.iconify.design/arcticons/

It would be a nice inclusion to this great tool :)

**Comment by EvaMarco** [comment]
Hello @Donnnno 
Just kindly remind you that we are open to contributions :), you have a guide [here](https://penpot.app/how-to-contribute.html).
Also if you can not contribute with this you can ask for help in the [community]( https://community.penpot.app/). 
Thanks¡¡
