### ISSUE TITLE
Prototyping Issues

### ISSUE THREAD

**Issue by divyansh98sharma** [penpot/penpot-files#19]
### Problem Statement

While using the prototyping feature of penpot, the components, shapes, or groups couldn't be prototyped without adding them on a board. The prototype panel says that you can select any shape, board, or groups and make the connections but that isn't possible without inscribing it on a board.

Screenshot for Reference

<img width="248" alt="Screenshot 2022-10-01 at 5 01 57 PM" src="https://user-images.githubusercontent.com/64745633/193407526-37cbd684-4eaf-49ee-92c5-b7f73d88e383.png">

### Intended Use Case

As a user, I want to quickly prototype any group, shape, or component and start working on the designs without adding a board on each block of design to make it responsive which would help to create interactive designs through which the stakeholders, product managers, and developers can understand what we as designers/user is trying to explain.

### User experience goal

User Persona: Product Designer
 - Motivations: 
 1. As a designer, I would want the developers to understand the feature in the most precise manner.

- Frustrations:
1. The interaction I want with the design won't be communicated and understood by the developer and the product manager properly if communicated verbally.
2. Adding a board behind every design is very time-consuming, and it might slip from the mind when the deadlines are approaching.

### Proposal

While prototyping every component, group, and shape should have a "+" icon linked to it which can be mapped with any other component, group, or shape.

### Further details

[Prototyping a component in Figma](https://www.youtube.com/watch?v=ReNbXhaL3Xk)

### What does success look like, and how can we measure that?

The current functionality for prototyping a component or anything for that matter has to have it inscribed on a board which is making the designers/users a little restless. The success over here is if the designer can directly add an interaction to the component without thinking about the board then the efficiency of all the designers would increase drastically and the user testing would be done way before the deadline of the feature and the communication between the designers, product managers, developers, and the stakeholders would be much easier.

**Comment by madalenapmelo-kp** [comment]
Hi @divyansh98sharma,

Thank you for the suggestion! While we appreciate that this would be useful for your use case, we do not plan to change the prototyping feature. 

We believe that allowing prototyping on any other layer outside of a board would add complexity and corner cases that would make it unmanageable, since boards are the design objects that can be considered independent design spaces.

That being said, we appreciate that the message displayed on the Prototype panel may be misleading and we will review it.

Thanks again for the feedback :slightly_smiling_face:
