### ISSUE TITLE
Support CC BY-SA

### ISSUE THREAD

**Issue by 12people** [penpot/penpot-files#2]
For fans of copyleft, it'd be great if this library accepted templates licensed under the open-source CC BY-SA license.

While this license has limited utility in corporate circles, it's a very useful and very commonly used license in FOSS circles.

One of the benefits of this license is that nobody can take the library, build upon it, and then sell the result under a non-free license. All derived works have to be released under the CC BY-SA license.

**Comment by niwinz** [comment]
This repo accepts libraries of any opensource license, the license listed right now is for the current content. If you contribute a library to this repo that has different license, just attach the license with the same name. I mean:

- `<name-of-library>.penpot`
- `<name-of-library>.license`

**Comment by niwinz** [comment]
Yes, we have this in our TODO, adding a good CONTRIBUTING.md file.
