### ISSUE TITLE
Material design 3

### ISSUE THREAD

**Issue by yuuyins** [penpot/penpot-files#22]
the current material design kit is outdated. Material design is the most popular design language, we need it, otherwise people will just use figma.

 https://m3.material.io/

**Comment by elhombretecla** [comment]
Hi @yuuyins Thank you so much for you feedback. We will create M3 library as soon as we can.

Meanwhile just kindly remind you that we are open to contributions :)

**Comment by myfunnyandy** [comment]
Hi @yuuyins, as @elhombretecla mentioned, we are willing to create the M3 library but thruth is that we are currently focused on the Penpot product development and it might be a while until we can make it into our priorities. You might want to ask for help at the community ast most of the templates are made by community members outside the Penpot team. There is an specific tag for libraries and templates that you could use: https://community.penpot.app/c/contributions/libraries-templates

**Comment by PapyElGringo** [comment]
Thanks everyone for the hard work. 
Adding my voice to this ( also related to #14) and I think this kind of major design system should ideally maintain by the core team to be sure it's updated.

**Comment by marcos-abreu** [comment]
I've recently (a week ago) started using penpot for some personal projects and I'm willing to create and share the library for "Material Design 3" on Penpot. I'm not a designer, but I have lots of experiences helping teams develop and integrate design systems. I've already started, and I can produce something that I can share soon.

**Comment by marcos-abreu** [comment]
@yuuyins - I'm a less than a week away from finishing my first version "Alpha Version". I've already created most of the components (aside from: menu, date picker and time picker). 30+ components and 350+ variations in total.

Next week I will be testing it, by creating some screens using my library and see how it adapts and see what I need to change based on real case scenarios. I would love to have someone else try it on their own personal projects, and give me some feedback to see if this is good for others to use as well.

@yuuyins  Let me know if you, and/or anyone else here is interested in helping me with early feeback.

ps: if there is different process in order to test and get feedback from the Penpot's team, please let me know and I will try to follow it.

**Comment by myfunnyandy** [comment]
Hi @marcos-abreu, Penpot core team member here :)

If you want early feedback specifically from the Penpot team, you can rise a PR right in this GitHub repo or you can send us the file to info@penpot.app. If you are open to suggestions from the Penpot community (and that includes the Penpot team), the best option would be to create a post [at the Community](https://community.penpot.app/c/contributions/10) under the Contributions category sharing whatever you feel it would be useful (your doubts, screenshots, the .penpot...).

This is one of the most requested libraries, we're looking forward to sharing it!

**Comment by marcos-abreu** [comment]
@myfunnyandy - Thanks for the information, I will be submitting a PR with the penpot file here sometime this week (at least this is the plan) and I will post in the Community Contributions forum with a link to the PR when I do.

I'm definitely open to suggestions, as I said I'm really new to Penpot.

Here is a link to the view mode of the components I have so far (with comments enabled from any Penpot user): https://design.penpot.app/#/view/f13ed095-e13f-808c-8002-2830d45911f7?page-id=ef68baf8-3d3e-8095-8002-3699280398e2&section=interactions&index=0&share-id=d9665a57-0073-80a2-8002-3b35af49d867

**Comment by marcos-abreu** [comment]
I've open a PR for Material Design 3. Again this is an initial PR with what I consider to be more like an Alpha version, I will be open to feedback from anyone that has the time to test it. I know there are lots I can improve since I'm new to Penpot. :)

PR #31

**Comment by coreyman** [comment]
> @myfunnyandy - Thanks for the information, I will be submitting a PR with the penpot file here sometime this week (at least this is the plan) and I will post in the Community Contributions forum with a link to the PR when I do.
> 
> I'm definitely open to suggestions, as I said I'm really new to Penpot.
> 
> Here is a link to the view mode of the components I have so far (with comments enabled from any Penpot user): https://design.penpot.app/#/view/f13ed095-e13f-808c-8002-2830d45911f7?page-id=ef68baf8-3d3e-8095-8002-3699280398e2&section=interactions&index=0&share-id=d9665a57-0073-80a2-8002-3b35af49d867

Can I please use this? There doesn't seem to be anything like this in https://penpot.app/libraries-templates that is not a paid kit besides maybe 'Ant Design UI Kit Lite'.

**Comment by coreyman** [comment]
> @coreyman we've just published it at the [Libraries & Templates](https://penpot.app/libraries-templates) page so you can already download it. We will probably add it to the in-app carousel too.
> 
> Thank you very much @marcos-abreu, this is a great contribution.

Thanks everybody!

**Comment by hernan930308** [comment]
thanks for the contribution, I have a problem when I change color to customize the penpot components it breaks
