### ISSUE TITLE
Create Webhook does not work

### ISSUE THREAD

**Issue by fsoft72** [penpot/penpot-files#26]
Hello, I was trying to set a webhook to see what kind of data is sent, but creating the webhook gives me an error.
The error is: `Something wrong has happened (on backend).`

I am attaching a screenshot.

![error](https://user-images.githubusercontent.com/2844375/215986998-ccaed0aa-8420-4457-911d-d9a12c2afe8a.png)

**Comment by superalex** [comment]
Hello @fsoft72 

I've checked the the server logs and it seems the url https://eogxl4zireuvi0d.m.pipedream.net is giving a timeout error. As the backend tries to validate the payload url it's failing, could you please create a webhook with a valid payload url?

**Comment by fsoft72** [comment]
Hello @superalex , now it works. I see the requests from your website and the test server sometimes is slow on responding (~3000ms) and I think this is what triggered the timeout.
By keeping the test server alive, I was able to add the webhook.

**Comment by superalex** [comment]
Great! :)
