### ISSUE TITLE
Webhooks cannot be created on the Docker version

### ISSUE THREAD

**Issue by fsoft72** [penpot/penpot-files#27]
On the docker version of PenPot (I have updated the docker images and now I am using `v1.17`), there is no option to create WebHooks.

![image](https://user-images.githubusercontent.com/2844375/215987270-6dcbe58c-b0e3-4599-b78f-26a959fdd3e4.png)

**Comment by superalex** [comment]
Hello @fsoft72 

webhooks are not enabled by default, check your docker-compose.yaml and check enable-webhooks is set :)
