### ISSUE TITLE
GNOME Components link broken

### ISSUE THREAD

**Issue by ChildishGiant** [penpot/penpot-files#28]
The link currently points to https://github.com/penpot/penpot-files/raw/main/GNOME%20Compontents.penpot
but should point to https://github.com/penpot/penpot-files/raw/main/GNOME-Components.penpot

This link is broken here: https://penpot.app/libraries-templates

**Comment by elhombretecla** [comment]
Hi @ChildishGiant thanks for the feedback :)

It is already fixed.
