### ISSUE TITLE
Unable to download Ant Design UI Kit from site

### ISSUE THREAD

**Issue by candidexmedia** [penpot/penpot-files#7]
[On the website](https://penpot.app/libraries-templates.html), trying to download the Ant Design UI kit brings an error:

![image](https://user-images.githubusercontent.com/95003834/145461064-348b829c-cdd3-41ab-a6c5-51f406e200fc.png)

The page leads to this link: https://github.com/penpot/penpot-files/raw/main/Ant-Design-UI-Kit-20Lite.penpot

Instead, it should link to: https://github.com/penpot/penpot-files/raw/main/Ant-Design-UI-Kit-Lite.penpot

**Comment by EvaMarco** [comment]
Hello Candide:
I'm sorry this post went by unnoticed. But I think is already fixed. Sorry.
