### ISSUE TITLE
Bootstrap Icons

### ISSUE THREAD

**Issue by vanillajonathan** [penpot/penpot-files#9]
I request a Penpot file for Bootstrap icons.

https://icons.getbootstrap.com/
https://github.com/twbs/icons

License: MIT License

**Comment by vanillajonathan** [comment]
https://github.com/twbs/icons/issues/1314

**Comment by EvaMarco** [comment]
Hello @vanillajonathan 
Just kindly remind you that we are open to contributions :), you have a guide [here](https://penpot.app/how-to-contribute.html).
Also if you can not contribute with this you can ask for help in the [community]( https://community.penpot.app/). 
Thanks¡¡
